/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AdsRouteImport } from './routes/ads'
import { Route as ReferRouteImport } from './routes/refer'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as ProfileIndexRouteImport } from './routes/profile.index'
import { Route as ProfileAboutRouteImport } from './routes/profile.about'
import { Route as ProfileLeaderboardRouteImport } from './routes/profile.leaderboard'
import { Route as ProfilePayoutsRouteImport } from './routes/profile.payouts'
import { Route as ProfileTransactionsRouteImport } from './routes/profile.transactions'
import { Route as ProfileWalletRouteImport } from './routes/profile.wallet'
import { Route as ApiPublicAdsPostbackRouteImport } from './routes/api/public/ads-postback'
import { Route as ApiPublicTelegramWebhookRouteImport } from './routes/api/public/telegram-webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdsRoute = AdsRouteImport.update({
  id: '/ads',
  path: '/ads',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferRoute = ReferRouteImport.update({
  id: '/refer',
  path: '/refer',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileAboutRoute = ProfileAboutRouteImport.update({
  id: '/profile/about',
  path: '/profile/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileLeaderboardRoute = ProfileLeaderboardRouteImport.update({
  id: '/profile/leaderboard',
  path: '/profile/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilePayoutsRoute = ProfilePayoutsRouteImport.update({
  id: '/profile/payouts',
  path: '/profile/payouts',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileTransactionsRoute = ProfileTransactionsRouteImport.update({
  id: '/profile/transactions',
  path: '/profile/transactions',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileWalletRoute = ProfileWalletRouteImport.update({
  id: '/profile/wallet',
  path: '/profile/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAdsPostbackRoute = ApiPublicAdsPostbackRouteImport.update({
  id: '/api/public/ads-postback',
  path: '/api/public/ads-postback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTelegramWebhookRoute =
  ApiPublicTelegramWebhookRouteImport.update({
    id: '/api/public/telegram-webhook',
    path: '/api/public/telegram-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/ads': typeof AdsRoute
  '/refer': typeof ReferRoute
  '/tasks': typeof TasksRoute
  '/profile/about': typeof ProfileAboutRoute
  '/profile/leaderboard': typeof ProfileLeaderboardRoute
  '/profile/payouts': typeof ProfilePayoutsRoute
  '/profile/transactions': typeof ProfileTransactionsRoute
  '/profile/wallet': typeof ProfileWalletRoute
  '/profile/': typeof ProfileIndexRoute
  '/api/public/ads-postback': typeof ApiPublicAdsPostbackRoute
  '/api/public/telegram-webhook': typeof ApiPublicTelegramWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/ads': typeof AdsRoute
  '/refer': typeof ReferRoute
  '/tasks': typeof TasksRoute
  '/profile/about': typeof ProfileAboutRoute
  '/profile/leaderboard': typeof ProfileLeaderboardRoute
  '/profile/payouts': typeof ProfilePayoutsRoute
  '/profile/transactions': typeof ProfileTransactionsRoute
  '/profile/wallet': typeof ProfileWalletRoute
  '/profile': typeof ProfileIndexRoute
  '/api/public/ads-postback': typeof ApiPublicAdsPostbackRoute
  '/api/public/telegram-webhook': typeof ApiPublicTelegramWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/ads': typeof AdsRoute
  '/refer': typeof ReferRoute
  '/tasks': typeof TasksRoute
  '/profile/about': typeof ProfileAboutRoute
  '/profile/leaderboard': typeof ProfileLeaderboardRoute
  '/profile/payouts': typeof ProfilePayoutsRoute
  '/profile/transactions': typeof ProfileTransactionsRoute
  '/profile/wallet': typeof ProfileWalletRoute
  '/profile/': typeof ProfileIndexRoute
  '/api/public/ads-postback': typeof ApiPublicAdsPostbackRoute
  '/api/public/telegram-webhook': typeof ApiPublicTelegramWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/ads'
    | '/refer'
    | '/tasks'
    | '/profile/about'
    | '/profile/leaderboard'
    | '/profile/payouts'
    | '/profile/transactions'
    | '/profile/wallet'
    | '/profile/'
    | '/api/public/ads-postback'
    | '/api/public/telegram-webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/ads'
    | '/refer'
    | '/tasks'
    | '/profile/about'
    | '/profile/leaderboard'
    | '/profile/payouts'
    | '/profile/transactions'
    | '/profile/wallet'
    | '/profile'
    | '/api/public/ads-postback'
    | '/api/public/telegram-webhook'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/ads'
    | '/refer'
    | '/tasks'
    | '/profile/about'
    | '/profile/leaderboard'
    | '/profile/payouts'
    | '/profile/transactions'
    | '/profile/wallet'
    | '/profile/'
    | '/api/public/ads-postback'
    | '/api/public/telegram-webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AdsRoute: typeof AdsRoute
  ReferRoute: typeof ReferRoute
  TasksRoute: typeof TasksRoute
  ProfileAboutRoute: typeof ProfileAboutRoute
  ProfileLeaderboardRoute: typeof ProfileLeaderboardRoute
  ProfilePayoutsRoute: typeof ProfilePayoutsRoute
  ProfileTransactionsRoute: typeof ProfileTransactionsRoute
  ProfileWalletRoute: typeof ProfileWalletRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
  ApiPublicAdsPostbackRoute: typeof ApiPublicAdsPostbackRoute
  ApiPublicTelegramWebhookRoute: typeof ApiPublicTelegramWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ads': {
      id: '/ads'
      path: '/ads'
      fullPath: '/ads'
      preLoaderRoute: typeof AdsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refer': {
      id: '/refer'
      path: '/refer'
      fullPath: '/refer'
      preLoaderRoute: typeof ReferRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/': {
      id: '/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/about': {
      id: '/profile/about'
      path: '/profile/about'
      fullPath: '/profile/about'
      preLoaderRoute: typeof ProfileAboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/leaderboard': {
      id: '/profile/leaderboard'
      path: '/profile/leaderboard'
      fullPath: '/profile/leaderboard'
      preLoaderRoute: typeof ProfileLeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/payouts': {
      id: '/profile/payouts'
      path: '/profile/payouts'
      fullPath: '/profile/payouts'
      preLoaderRoute: typeof ProfilePayoutsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/transactions': {
      id: '/profile/transactions'
      path: '/profile/transactions'
      fullPath: '/profile/transactions'
      preLoaderRoute: typeof ProfileTransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/wallet': {
      id: '/profile/wallet'
      path: '/profile/wallet'
      fullPath: '/profile/wallet'
      preLoaderRoute: typeof ProfileWalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ads-postback': {
      id: '/api/public/ads-postback'
      path: '/api/public/ads-postback'
      fullPath: '/api/public/ads-postback'
      preLoaderRoute: typeof ApiPublicAdsPostbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/telegram-webhook': {
      id: '/api/public/telegram-webhook'
      path: '/api/public/telegram-webhook'
      fullPath: '/api/public/telegram-webhook'
      preLoaderRoute: typeof ApiPublicTelegramWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AdsRoute: AdsRoute,
  ReferRoute: ReferRoute,
  TasksRoute: TasksRoute,
  ProfileAboutRoute: ProfileAboutRoute,
  ProfileLeaderboardRoute: ProfileLeaderboardRoute,
  ProfilePayoutsRoute: ProfilePayoutsRoute,
  ProfileTransactionsRoute: ProfileTransactionsRoute,
  ProfileWalletRoute: ProfileWalletRoute,
  ProfileIndexRoute: ProfileIndexRoute,
  ApiPublicAdsPostbackRoute: ApiPublicAdsPostbackRoute,
  ApiPublicTelegramWebhookRoute: ApiPublicTelegramWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
